spring.datasource.url: jdbc:mysql://49.235.231.67:3306/ctpc?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
spring.datasource.username: your username
spring.datasource.password: your password
spring.datasource.driver-class-name: com.mysql.cj.jdbc.Driver
server.port: 443 
server.ssl.enable: true
server.ssl.key-store: address of SSL varify
server.ssl.key-store-password: your SSL private password
server.ssl.key-store-type: like JKS or somethings
