spring.datasource.url: jdbc:mysql://49.235.231.67:3306/ctpc?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
spring.datasource.username: nsplnpbjy
spring.datasource.password: bjy653300
spring.datasource.driver-class-name: com.mysql.cj.jdbc.Driver
server.port: 8031